apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadzxrq5602-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadzxrq5602-tenant-component
    app.kubernetes.io/part-of: loadzxrq5602-tenant-app
  name: loadzxrq5602-tenant-component
  namespace: loadzxrq5602-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadzxrq5602-tenant-component
    weight: null
status: {}
