apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadzxrq5602-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadzxrq5602-tenant-component
    app.kubernetes.io/part-of: loadzxrq5602-tenant-app
  name: loadzxrq5602-tenant-component
  namespace: loadzxrq5602-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadzxrq5602-tenant-component
status:
  loadBalancer: {}
